### ISSUE TITLE
pyirobot suddenly stopped working

### ISSUE THREAD

**Issue by amirshani** [cseelye/pyirobot#2]
I was working great but recently I got the following error

>>> robot.GetTime()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyirobot\__init__.py", line 344, in GetTime
    result = self._PostToRobot("get", "time")
  File "pyirobot\__init__.py", line 234, in _PostToRobot
    verify=False)
  File "c:\Python27\lib\site-packages\requests-2.12.3-py2.7.egg\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\Python27\lib\site-packages\requests-2.12.3-py2.7.egg\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Python27\lib\site-packages\requests-2.12.3-py2.7.egg\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Python27\lib\site-packages\requests-2.12.3-py2.7.egg\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "c:\Python27\lib\site-packages\requests-2.12.3-py2.7.egg\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.0.0.62', port=443): Max retries exceeded with url: /umi (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x032F68D0>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
>>>

**Comment by cseelye** [comment]
I would guess either one of two things.  Either your robot has changed DHCP IP address, or your robot got a new firmware update from iRobot.

It looks like iRobot has been slowly pushing out a new firmware to robots that disables HTTPS and uses a different protocol (looks like MQTT on port 8883).  If you look the firmware version of your robot in the phone app and it is 2.0 then that is probably the problem.

**Comment by amirshani** [comment]
Yup, you are right, I have firmware version v2.0.0-34
Thanks anyway :)
